export const POKEMONS = [
    {
      "Code": 1,
      "Category": "種子寶可夢",
      "ChineseName": "妙蛙種子",
      "EnglishName": "Bulbasaur",
      "Description": "經常可見牠在太陽下睡午覺的樣子。在沐浴了充足的陽光之後，牠背上的種子就會成長茁壯。",
      "Img": "assets/images/Pokemon/Bulbasaur.png",
      "Types":[{"Name":"草"},{"Name":"毒"}],
      "Height":"0.7",
      "Weight":"6.9"
    },
    {
      "Code": 2,
      "Category": "蜥蜴寶可夢",
      "ChineseName": "小火龍",
      "EnglishName": "Charmander",
      "Description": "天生喜歡熱熱的東西。據說當牠被雨淋濕的時候，尾巴的末端會冒出煙來。",
      "Img": "assets/images/Pokemon/Charmander.png",
      "Types":[{"Name":"火"}],
      "Height":"0.6",
      "Weight":"8.5"
    },
    {
      "Code": 3,
      "Category": "火焰寶可夢",
      "ChineseName": "噴火龍",
      "EnglishName": "Charizard",
      "Description": "會噴出彷彿連岩石都能燒焦的灼熱火焰。有時會引發森林火災。",
      "Img": "assets/images/Pokemon/Charizard.png",
      "Types":[{"Name":"火"},{"Name":"飛行"}],
      "Height":"1.7",
      "Weight":"90.5"
    },
    {
      "Code": 4,
      "Category": "小龜寶可夢",
      "ChineseName": "傑尼龜",
      "EnglishName": "Squirtle",
      "Description": "甲殼的作用不僅是用來保護自己，圓潤的外形和表面的溝槽會減少水的阻力，使牠能夠快速地游泳。",
      "Img": "assets/images/Pokemon/Squirtle.png",
      "Types":[{"Name":"水"}],
      "Height":"0.5",
      "Weight":"9.0"
    },
    {
      "Code": 5,
      "Category": "鳥寶可夢",
      "ChineseName": "大比鳥",
      "EnglishName": "Pidgeot",
      "Description": "有著亮麗羽毛的寶可夢。有許多訓練家被大比鳥頭上美麗的羽毛深深吸引而開始培育牠。",
      "Img": "assets/images/Pokemon/Pidgeot.png",
      "Types":[{"Name":"一般"},{"Name":"飛行"}],
      "Height":"1.5",
      "Weight":"39.5"
    },
    {
      "Code": 6,
      "Category": "眼鏡蛇寶可夢",
      "ChineseName": "阿柏怪",
      "EnglishName": "Arbok",
      "Description": "最新的研究結果顯示，牠們肚子上的花紋有２０種以上的不同圖案。",
      "Img": "assets/images/Pokemon/Arbok.png",
      "Types":[{"Name":"毒"}],
      "Height":"3.5",
      "Weight":"65.0"
    },
    {
      "Code": 7,
      "Category": "鼠寶可夢",
      "ChineseName": "皮卡丘",
      "EnglishName": "Pikachu",
      "Description": "越是能製造出強大電流的皮卡丘，臉頰上的囊就越柔軟，同時也越有伸展性。",
      "Img": "assets/images/Pokemon/Pikachu.png",
      "Types":[{"Name":"電"}],
      "Height":"0.4",
      "Weight":"6.0"
    },
    {
      "Code": 8,
      "Category": "妖精寶可夢",
      "ChineseName": "皮皮",
      "EnglishName": "Vulpix",
      "Description": "據說如果在滿月的夜晚看見皮皮們聚在一起跳舞，就能得到幸福。",
      "Img": "assets/images/Pokemon/Vulpix.png",
      "Types":[{"Name":"妖精"}],
      "Height":"0.6",
      "Weight":"7.5"
    },
    {
      "Code": 9,
      "Category": "狐狸寶可夢",
      "ChineseName": "六尾",
      "EnglishName": "Clefairy",
      "Description": "雖然還是孩子，但已擁有美麗的６根尾巴。長大後尾巴會變得更多。",
      "Img": "assets/images/Pokemon/Clefairy.png",
      "Types":[{"Name":"火"}],
      "Height":"0.6",
      "Weight":"9.9"
    },
    {
      "Code": 10,
      "Category": "狐狸寶可夢",
      "ChineseName": "九尾",
      "EnglishName": "Ninetales",
      "Description": "每一根尾巴裡都蘊含著神通力。據說牠的壽命長達１０００年。",
      "Img": "assets/images/Pokemon/Ninetales.png",
      "Types":[{"Name":"火"}],
      "Height":"1.1",
      "Weight":"19.9"
    },
    {
      "Code": 11,
      "Category":"氣球寶可夢",
      "ChineseName": "胖丁",
      "EnglishName": "Jigglypuff",
      "Description": "在百貨公司的寢具區可以買到收錄著胖丁那奇妙搖籃曲的ＣＤ。",
      "Img": "assets/images/Pokemon/Jigglypuff.png",
      "Types":[{"Name":"一般"},{"Name":"妖精"}],
      "Height":"0.5",
      "Weight":"5.5"
    },
    {
      "Code": 12,
      "Category": "雜草寶可夢",
      "ChineseName": "走路草",
      "EnglishName": "Oddish",
      "Description": "沐浴月光就會開始活動。為了四處散播種子，會在夜晚到處走動。",
      "Img": "assets/images/Pokemon/Oddish.png",
      "Types":[{"Name":"草"},{"Name":"毒"}],
      "Height":"0.5",
      "Weight":"5.4"
    },
    {
      "Code": 13,
      "Category": "鼴鼠寶可夢",
      "ChineseName": "地鼠",
      "EnglishName": "Diglett",
      "Description": "地鼠經過之後的土壤會得到適當的翻動，成為最適合耕種的田地。",
      "Img": "assets/images/Pokemon/Diglett.png",
      "Types":[{"Name":"地面"}],
      "Height":"0.2",
      "Weight":"0.8"
    },
    {
      "Code": 14,
      "Category": "妖怪貓寶可夢",
      "ChineseName": "喵喵",
      "EnglishName": "Meowth",
      "Description": "喜歡收集亮晶晶的東西。當牠心情好的時候，會讓訓練家一起欣賞自己的收藏。",
      "Img": "assets/images/Pokemon/Meowth.png",
      "Types":[{"Name":"一般"}],
      "Height":"0.4",
      "Weight":"4.2"
    },
    {
      "Code": 15,
      "Category": "鴨寶可夢",
      "ChineseName": "可達鴨",
      "EnglishName": "Psyduck",
      "Description": "一使出念力就會頭痛，所以平常盡量什麼事都不做，整天不停地發呆。",
      "Img": "assets/images/Pokemon/Psyduck.png",
      "Types":[{"Name":"水"}],
      "Height":"0.9",
      "Weight":"19.6"
    },
    {
      "Code": 16,
      "Category": "怪力寶可夢",
      "ChineseName": "腕力",
      "EnglishName": "Machop",
      "Description": "全身都是肌肉，雖然體型只有小孩那麼大，卻可以扔飛１００個大人。",
      "Img": "assets/images/Pokemon/Machop.png",
      "Types":[{"Name":"格鬥"}],
      "Height":"0.8",
      "Weight":"19.5"
    },
    {
      "Code": 17,
      "Category": "火馬寶可夢",
      "ChineseName": "小火馬",
      "EnglishName": "Ponyta",
      "Description": "剛出生的時候不擅長奔跑，但隨著和夥伴們不斷地賽跑，會逐漸鍛鍊出強健的腳力。",
      "Img": "assets/images/Pokemon/Ponyta.png",
      "Types":[{"Name":"火"}],
      "Height":"1.0",
      "Weight":"30.0"
    },
    {
      "Code": 18,
      "Category":"憨憨寶可夢",
      "ChineseName": "呆呆獸",
      "EnglishName": "Slowpoke",
      "Description": "傳說當呆呆獸打呵欠時就會開始下雨，所以據說有些地區會祭祀呆呆獸。",
      "Img": "assets/images/Pokemon/Slowpoke.png",
      "Types":[{"Name":"水"},{"Name":"超能力"}],
      "Height":"1.2",
      "Weight":"36.0"
    },
    {
      "Code": 19,
      "Category": "魚寶可夢",
      "ChineseName": "鯉魚王",
      "EnglishName": "Magikarp",
      "Description": "力量和速度都不太行。是世界上最弱最可憐的寶可夢。",
      "Img": "assets/images/Pokemon/Magikarp.png",
      "Types":[{"Name":"水"}],
      "Height":"0.9",
      "Weight":"10.0"
    },
    {
      "Code": 20,
      "Category":"進化寶可夢",
      "ChineseName": "伊布",
      "EnglishName": "Eevee",
      "Description":"伊布擁有著能夠為了適應周遭的環境而改變身體構造的能力。",
      "Img": "assets/images/Pokemon/Eevee.png",
      "Types":[{"Name":"一般"}],
      "Height":"0.3",
      "Weight":"6.5"
    }
  ]